#!/bin/bash

if [ -z "${1}" ] || [ "${1}" = "--help" ]; then
 echo "usage: ${0} [PATH] [--demo] [[--full]|[--ver XYZ]]? mysql_params db_name"
 echo
 echo " PATH         - path containing .SQL upgrade files, '.' by default"
 echo " --demo       - use additional .SQL scripts to fill db with demo data"
 echo " --full       - execute all UP*.SQL scripts upto the latest version"
 echo " --ver XYZ    - update to version specified by XYZ, can't combine with --full"
 echo " mysql_params - parameters to connect to database, as given to mysql client"
 echo " db_name      - name of the database to update"
 echo
 exit 0
fi

VERSION_LENGTH=3
BINPATH=$( dirname "${0}" )

SQLPATH=
if [[ -d ${1} ]]; then
 SQLPATH="${1}/"
 shift
fi

DEMO=0
if [ ${1} = "--demo" ]; then
 DEMO=1
 shift
fi

FULL=0
if [ ${1} = "--full" ]; then
 FULL=1
 shift
fi

TVER=""
if [ ${1} = "--ver" ]; then
 shift
 TVER=${1}
 ACTUAL_LENGTH=${#TVER}
 if [ $ACTUAL_LENGTH -ne $VERSION_LENGTH ]; then
  echo "${0}: invalid version: expecting three digits, zero-padded to the left"
  exit 1
 fi
 if [[ ! ${TVER} =~ ^[0-9]+$ ]]; then
  echo "${0}: invalid version: expecting three digits, zero-padded to the left"
  exit 1
 fi
 shift
fi

if [[ $FULL -eq 1 ]] && [ ! $TVER = "" ]; then
 echo "${0}: can't combine --full and --ver flags"
 exit 1
fi

if [ ! ${TVER} = "" ]; then
 FULL=1
fi

DB=${@:$#}

ERR=1
while [[ $ERR -ne 0 ]]; do
 mysql ${*%${!#}} -e "CREATE DATABASE IF NOT EXISTS ${DB};" 2> /dev/null
 ERR=$?
 if [[ ${ERR} -ne 0 ]]; then
  SLEEPTIME=$[ ( ${RANDOM} % 10 ) + 5 ]s
  echo "$0: Database not yet available; waiting ${SLEEPTIME}"
  sleep ${SLEEPTIME}
 fi
done

VER=`mysql ${*%${!#}} -e "USE ${DB}; SELECT IF(EXISTS(SELECT SCHEMA_NAME FROM INFORMATION_SCHEMA.SCHEMATA WHERE SCHEMA_NAME = '${DB}'),
                                            IF(EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = '${DB}' AND TABLE_NAME = 'setting'),
                                            IF(((SELECT settingValue FROM setting WHERE settingName = 'dbVersion') IS NULL), '000',
                                                (SELECT settingValue FROM setting WHERE settingName = 'dbVersion')), '000'), '000') Ver;" 2> /dev/null | sed 's/ *$//'`

VER=$(echo ${VER} | awk '{print $2}')

if [ -z "${VER}" ]; then
 VER="000"
 NOVER=1
fi

SVER=${VER}

if [ "${TVER}" = "${VER}" ]; then
 echo "${0}: database is already at version ${TVER}: nothing to do"
 exit 0
fi
if [ ! "${TVER}" = "" ]; then
 if [ "${TVER}" -lt "${VER}" ]; then
  echo "${0}: specified --ver (${TVER}) is lower than database version (${VER}): exiting"
  exit 1
 fi
fi

ERR=0
F=fakefile.sql
while [ ! -z ${F} ] && { [ "${TVER}" = "" ] || [ "${TVER}" -gt "${VER}" ]; } do
 VER="`printf %03g $((10#${VER} + 1))`"
 FILE="${SQLPATH}UP_${VER}_Version_"
 FOUND=0
 for F in `ls "${FILE}"* 2> /dev/null`; do
  FOUND=1
  if [ -z "${NOVER}" ]; then
   mysql $@ < "${F}"
   ERR=$?
  else
   mysql ${@:1:$#-1} < "${F}"
   ERR=$?
   unset NOVER
  fi
  if [ $ERR -eq 0 ] && [ ! -z ${F} ]; then
   echo "$0: Updated database '${DB}' to version ${VER}"
  fi
 done

 if [ ${FOUND} -eq 0 ] || [ ${FULL} -eq 0 ] || [ ${ERR} -ne 0 ]; then
  unset F
 fi

 if [ ${DEMO} -eq 1 ] && [ ! -z ${F} ]; then
  DEMOFILE="${SQLPATH}DEMOPUT_${VER}.sql"
  if [[ -f ${DEMOFILE} ]]; then
   mysql $@ < "${DEMOFILE}"
   if [ $? -eq 0 ]; then
    echo "$0: Successfully applied demo script for version ${VER}."
   else
    echo "$0: Failed applying demo script for version ${VER}."
   fi
  fi
 fi
done

if [ ${ERR} -ne 0 ]; then
 echo "$0: There were errors in SQL scripts (version ${VER})."
 NVER=`mysql ${*%${!#}} -e "USE ${DB}; SELECT IF(EXISTS(SELECT SCHEMA_NAME FROM INFORMATION_SCHEMA.SCHEMATA WHERE SCHEMA_NAME = '${DB}'),
                                              IF(EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = '${DB}' AND TABLE_NAME = 'setting'),
                                              IF(((SELECT settingValue FROM setting WHERE settingName = 'dbVersion') IS NULL), '000',
                                                  (SELECT settingValue FROM setting WHERE settingName = 'dbVersion')), '000'), '000') Ver;" 2> /dev/null | sed 's/ *$//'`
 
 NVER=$(echo ${NVER} | awk '{print $2}')
 if [ "${SVER}" -lt "${VER}" ]; then
  echo "${0}: attempting to run the downgrade script back to previous version"
  "${BINPATH}/dbdowngrade" "${SQLPATH}" $@
 fi
fi

if [ ! "${TVER}" = "" ]; then
 if [ "${TVER}" -gt "${VER}" ]; then
  echo "${0}: no more update files: can't update to specified --ver (${TVER})"
 fi
fi