on: [push]

jobs:
  build_image:
    runs-on: ubuntu-latest
    name: Image builder job
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Build image
        run: |
          docker build . -t helloworldimage -f docker-action/Dockerfile
          docker save $(docker images | grep helloworldimage | awk '{print $3}') helloworldimage:$(docker images | grep helloworldimage | awk '{print $2}') | gzip > helloworldimage.tar.gz
      - name: Upload image
        uses: actions/upload-artifact@v2
        with:
          name: helloworldimage
          path: helloworldimage.tar.gz

  scp_image:
    name: SCP image
    needs: build_image
    runs-on: ubuntu-latest
    steps:
      - name: Download image
        uses: actions/download-artifact@v2
        with:
          name: helloworldimage
      - name: Copy via scp
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          source: "helloworldimage.tar.gz"
          target: "helloworldimage"
    
